#BEGIN VOXEL STUFF
map_type: voxel
origin_z: 0.0
z_voxels: 6 
z_resolution: 0.23
unknown_threshold: 7
mark_threshold: 0
#END VOXEL STUFF
transform_tolerance: 0.2
obstacle_range: 2.5
raytrace_range: 3.0
#  inscribed_radius: 0.325
circumscribed_radius: 0.46
inflation_radius: 0.55
cost_scaling_factor: 10.0
lethal_cost_threshold: 100

# BEGIN VOXEL STUFF
observation_sources: base_scan_marking base_scan tilt_scan ground_object_cloud

base_scan_marking: {sensor_frame: base_laser_link, data_type: PointCloud, expected_update_rate: 0.2,
  observation_persistence: 0.0, marking: true, clearing: false, min_obstacle_height: 0.08, max_obstacle_height: 2.0}

base_scan: {sensor_frame: base_laser_link, data_type: LaserScan, expected_update_rate: 0.2,
             observation_persistence: 0.0, marking: false, clearing: true, min_obstacle_height: -0.10, max_obstacle_height: 2.0}

tilt_scan: {sensor_frame: laser_tilt_link, data_type: LaserScan, expected_update_rate: 0.2,
             observation_persistence: 0.2, marking: false, clearing: true, min_obstacle_height: -20.00, max_obstacle_height: 40.0}

ground_object_cloud: {sensor_frame: laser_tilt_link, data_type: PointCloud, expected_update_rate: 0.2,
                       observation_persistence: 3.0, marking: true, clearing: false, min_obstacle_height: -0.10, max_obstacle_height: 2.0}
# END VOXEL STUFF
